import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Play,ArrowRight,X,Image as ImageIcon,Film}from'lucide-react';import'./styles.css';
const spaces=[
['Entry + Corridor','/images/corridor.webp','The Technology & AI Center arrival sequence introduces Hampton’s technology identity through immersive graphics, digital displays and a modern student-centered environment.',['/images/corridor.webp','/images/entry-1.webp','/images/entry-2.webp','/images/entry-3.webp','/images/entry-4.webp','/images/entry-5.webp']],
['Learning Pods','/images/learning-pods.webp','Flexible collaboration spaces that can adapt to the needs of Hampton academic programs while supporting technology-rich learning and secure access.',['/images/learning-pods.webp','/images/meeting-room.webp','/images/meeting-room-overhead.webp']],
['Presentation Room','/images/presentation-room.webp','A flexible presentation and meeting environment for training, workshops, certification programs and collaborative sessions, with a large screen as the focal point.',['/images/presentation-room.webp','/images/presentation-overhead.webp']],
['Esports Gaming Arena','/images/esports-room.webp','A dedicated and secure environment for esports tournaments, training, gaming computers and the game library.',['/images/esports-room.webp','/images/esports-scoreboard.webp','/images/esports-identity.webp']]
];
function Btn({children,onClick,ghost=false}){return <button className={ghost?'btn ghost':'btn'} onClick={onClick}>{children}<ArrowRight size={16}/></button>}
function App(){const[page,setPage]=useState('Home'),[modal,setModal]=useState(null);const go=p=>{setPage(p);scrollTo({top:0,behavior:'smooth'})};const tabs=['Vision','Spaces','Technology','Esports','Safety','Videos','Contact'];return <div><header><button className="wordmark" aria-label="Home" onClick={()=>go('Home')}><img src="/images/hampton-logo-exact.png" alt="Hampton University"/></button><nav>{tabs.map(t=><button key={t} className={page===t?'active':''} onClick={()=>go(t)}>{t}</button>)}</nav><Btn onClick={()=>go('Invest')}>INVEST NOW</Btn></header><main>{page==='Home'?<Home go={go}/>:page==='Vision'?<Vision/>:page==='Spaces'?<Explore setModal={setModal}/>:page==='Technology'?<Technology/>:page==='Esports'?<Esports go={go}/>:page==='Safety'?<Safety/>:page==='Videos'?<Videos/>:page==='Invest'?<Invest go={go}/>:<Contact/>}</main><footer><b>HAMPTON UNIVERSITY · TECHNOLOGY & AI CENTER</b><span>THE STANDARD OF EXCELLENCE</span></footer>{modal&&<Modal data={modal} close={()=>setModal(null)}/>}</div>}
function Home({go}){return <><section className="hero"><div className="heroCopy"><span className="kicker">HAMPTON UNIVERSITY · TECHNOLOGY & AI CENTER</span><h1>THE FUTURE<br/>LIVES <i>HERE.</i></h1><p>A collaborative research and learning environment built around immersive technology, AI, robotics, esports and the ideas that come next.</p><div className="row"><Btn onClick={()=>go('Spaces')}>EXPLORE THE CENTER</Btn><Btn ghost onClick={()=>go('Videos')}><Play size={15}/> WATCH THE VISION</Btn></div></div><div className="trueHolo"><img src="/images/entry-3.webp"/><span>HAMPTON UNIVERSITY // TECHNOLOGY & AI CENTER</span></div></section><section className="split"><img src="/images/president-lounge.webp"/><div><span className="kicker">PEOPLE · PURPOSE · POSSIBILITIES</span><h2>THE STANDARD OF EXCELLENCE, REIMAGINED.</h2><p>A technology-rich center envisioned to support learning, research, collaboration, career development and industry partnership.</p><Btn onClick={()=>go('Spaces')}>ENTER SPACES</Btn></div></section></>}
function Vision(){return <><section className="pageHero"><span className="kicker">VISION</span><h1>THE STANDARD OF EXCELLENCE, REIMAGINED.</h1><p>The Technology & AI Center is envisioned as a flexible research and learning facility inside the Hampton Student Center—supporting science, engineering, healthcare, creative technology, career development and industry partnership.</p></section><section className="wideImage"><img src="/images/entry-2.webp"/></section></>}
function Explore({setModal}){return <><section className="pageHero"><span className="kicker">SPACES</span><h1>EXPLORE OUR IMMERSIVE SPACES.</h1><p>Technology-driven environments for learning, research and real-world experience.</p></section><section className="spaceCardGrid">{spaces.map(s=><article className="spaceCard" key={s[0]} onClick={()=>setModal(s)}><img src={s[1]}/><div><h2>{s[0]}</h2><button>→</button><small>PHOTO + VIDEO GALLERY</small></div></article>)}</section></>}
function Technology(){return <><section className="pageHero"><span className="kicker">TECHNOLOGY</span><h1>BUILT FOR WHAT COMES NEXT.</h1><p>Immersive computing, AI, digital collaboration and advanced learning environments are integrated throughout the Center.</p></section><section className="gallery3"><img src="/images/corridor.webp"/><img src="/images/entry-3.webp"/><img src="/images/hu-globe.webp"/></section></>}
function Esports({go}){return <><section className="esHero"><img src="/images/esports-scoreboard.webp"/><div><span className="kicker">HAMPTON ESPORTS</span><h1>PLAY.<br/>COMPETE.<br/>CREATE.</h1><p>A dedicated digital competition and creative technology experience for students, teams and media production.</p><Btn onClick={()=>go('Videos')}>WATCH ESPORTS EXPERIENCE</Btn></div></section><section className="esportsIdentity"><img src="/images/esports-identity.webp"/><div><span className="kicker">COMPETITION · TECHNOLOGY · COMMUNITY</span><h2>A HOME FOR HAMPTON ESPORTS.</h2><p>The Gaming Arena is planned as a dedicated, secure space for esports tournaments and training, with opportunities to connect gaming to computing, broadcasting, production, teamwork and creative technology.</p></div></section></>}
function Safety(){return <><section className="pageHero"><span className="kicker">SAFETY + STANDARDS</span><h1>INNOVATION, RESPONSIBLY.</h1><p>Specialized equipment will be used in accordance with Hampton University policies, manufacturer guidance, training requirements and applicable safety standards.</p></section><section className="standards safetyText">{['Equipment-use protocols','Supervised access','VR / XR safety','Robotics + drone operations','Data + privacy','Accessibility','Emergency procedures','Training requirements'].map((x,i)=><article key={x}><b>{String(i+1).padStart(2,'0')}</b><h3>{x}</h3><p>Center operations will follow Hampton-approved procedures and applicable requirements.</p></article>)}</section></>}
function Videos(){const videos=[
  {title:'IMMERSIVE / VR LAB',id:'1233506757'},
  {title:'E-SPORTS LOUNGE',id:'1233505177'},
  {title:'PRESENTATION ROOM HTAIC',id:'1233481388'}
];return <><section className="pageHero"><span className="kicker">VIDEO EXPERIENCES</span><h1>SEE THE CENTER IN MOTION.</h1><p>Explore the Hampton Technology & AI Center through three immersive video experiences.</p></section><section className="videoGrid threeOnly">{videos.map(v=><article key={v.id}><div className="videoCardEmbed vimeoEmbed"><iframe src={`https://player.vimeo.com/video/${v.id}?badge=0&autopause=0&player_id=0&app_id=58479&autoplay=1&muted=1&loop=1`} frameBorder="0" allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share" referrerPolicy="strict-origin-when-cross-origin" title={v.title} allowFullScreen></iframe></div><h3>{v.title}</h3><span>WATCH VIDEO</span></article>)}</section></>}
function Contact(){return <><section className="pageHero"><span className="kicker">CONTACT</span><h1>CONNECT WITH THE CENTER.</h1><p>Hampton-approved project and campaign contact information can be placed here.</p></section><section className="wideImage"><img src="/images/entry-1.webp"/></section></>}
function Invest({go}){return <div className="investPage"><header className="investSubnav"><button onClick={()=>go('Home')} className="investLogo"><img src="/images/hampton-logo-exact.png"/></button><span>TECHNOLOGY & AI CENTER</span></header><section className="investWrap"><div className="investTitle"><span>SUPPORT INNOVATION</span><h1>Invest in the Future</h1><p>Your support helps advance immersive learning, research and innovation for Hampton students and faculty.</p></div><div className="donationGrid"><form className="donationForm" onSubmit={e=>{e.preventDefault();alert('Demonstration only — no payment information was submitted or stored.')}}><h3>Choose an Amount</h3><div className="amounts"><button type="button">$50</button><button type="button">$100</button><button type="button">$250</button><button type="button">$500</button><button type="button">Custom Amount</button></div><h3>Payment Method</h3><label>Cardholder / Account Holder Name<input placeholder="Full name"/></label><label>Payment Information<input placeholder="Demo only — no information is processed"/></label><button className="completeDemo">Complete Donation (Demo)</button><small className="demoNote">DEMONSTRATION ONLY · No real payment will be processed or stored.</small></form><aside className="impactPanel"><div><b>Make a Lasting Impact</b><p>Your investment supports hands-on student learning, interdisciplinary research and technology-rich spaces.</p></div></aside></div></section></div>}
function Modal({data,close}){const[idx,setIdx]=useState(0),gallery=data[3];return <div className="modal galleryModal" onClick={close}><div className="galleryShell" onClick={e=>e.stopPropagation()}><button className="close" onClick={close}><X/></button><button className="backLink" onClick={close}>← BACK TO SPACES</button><div className="galleryHead"><div><h2>{data[0]}</h2><small>SPACE GALLERY</small></div><div className="galleryTabs"><button className="selected"><ImageIcon/> PHOTO GALLERY</button><button><Film/> VIDEO GALLERY</button></div></div><div className="galleryLayout"><aside>{gallery.map((im,i)=><button className={i===idx?'thumb activeThumb':'thumb'} onClick={()=>setIdx(i)} key={im}><img src={im}/></button>)}</aside><div className="galleryMain"><div className="galleryImage"><img src={gallery[idx]}/></div><div className="galleryInfo"><div><h3>Space Overview</h3><p>{data[2]}</p></div></div></div></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
